### ISSUE TITLE
Suggestion : Check the right firmware

### ISSUE THREAD

**Issue by itsjustvenky** [scottchiefbaker/ESP-WebOTA#1]
Hi, 

You project is very good and I really liked it.
There is one flaw, that is your code doesn't do any check's for the correct firmware. If will update whichever firmware we provide.

Thanks
Venkat

**Comment by scottchiefbaker** [comment]
This would be a great feature, but I don't know if it's possible to verify a local file before uploading it. Any ideas how we would accomplish this?

**Comment by scottchiefbaker** [comment]
Any updates on this?
