### ISSUE TITLE
Use with WiFiManager.h

### ISSUE THREAD

**Issue by bill-orange** [scottchiefbaker/ESP-WebOTA#2]
@scottchiefbaker Can your library somehow be used with WiFiManager.h?  On an unattached ESP32 it would be good to update and setup Wifi without tethering to a PC.

Please advise.

P.S.  Nice work.  Worked on the first try!

**Comment by scottchiefbaker** [comment]
Yes the two should work together just fine, but I haven't tried it. WebOTA binds to port 8080 by deault which should not conflict with WifiManager. 

I've never used WifiManager, so let me know your test results and I can update the docs.

**Comment by bill-orange** [comment]
Will do.  I will let you know the result.

Invoke WifiManager before `init_wifi(ssid, password, host);`  ?

**Comment by scottchiefbaker** [comment]
`init_wifi(ssid, password, host);` is just a wrapper around the regular joining WiFi stuff. I would anticipate that part would conflict with WifiManager?

For simplicity, connect to WiFi (however you do it) before running the OTA handle stuff. In my case I use `init_wifi()` because it simplifies the process of connecting to WiFi and starting mDNS.

**Comment by bill-orange** [comment]
@scottchiefbaker  Understand. What would I need to change in your .h or .cpp to make `init_mdns (host)` available to my sketch? If I run it rather than `init_wifi()`  I think we are there.

**Comment by scottchiefbaker** [comment]
Where did we leave this?

**Comment by bill-orange** [comment]
I am running, but with a modification to WebOTS.h as described above.  I am hesitant to recommend WebOTA.h be revised. I don’t know what the impact of this change would in other people’s situations.

**Comment by scottchiefbaker** [comment]
I just used WifiManager and WebOTA together in the same sketch with no changes required.
