### ISSUE TITLE
Error updating thru webota (2 different boards tested)

### ISSUE THREAD

**Issue by ajaybnl** [scottchiefbaker/ESP-WebOTA#6]
Firmware update initiated: ESP8266_RF433_HUB.ino.nodemcu.bin

Exception (0):
epc1=0x40202798 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffff950 end: 3fffffc0 offset: 01a0
3ffffaf0:  3ffee644 3ffee640 3ffee63c 00000100

BUT ESP8266 > Examples > WebUpdate Works

**Comment by scottchiefbaker** [comment]
Did you ever figure this out?

**Comment by scottchiefbaker** [comment]
Closing this due to lack of response. If it's still an issue let me know and we can reopen.
